#!/bin/bash

if [ ! -d $OPENSHIFT_DATA_DIR/blogs.dir ]; then
    mkdir $OPENSHIFT_DATA_DIR/blogs.dir
fi

if [ ! -d $OPENSHIFT_DATA_DIR/uploads ]; then
    mkdir $OPENSHIFT_DATA_DIR/uploads
fi

ln -sf ${OPENSHIFT_DATA_DIR}/blogs.dir ${OPENSHIFT_REPO_DIR}/php/wp-content/
ln -sf ${OPENSHIFT_DATA_DIR}/uploads   ${OPENSHIFT_REPO_DIR}/php/wp-content/
